[project]
name = "rsi"
version = "0.1.0"
description = "Project with RSI strategy"
authors = [
    {name = "SV",email = "gvardovski@icloud.com"}
]
config = "config.yaml"
requires-python = ">=3.13"
dependencies = [
    "pandas (>=2.3.3,<3.0.0)",
    "pandas-ta (>=0.4.71b0,<0.5.0)",
    "vectorbt (>=0.28.1,<0.29.0)",
    "anywidget (>=0.9.21,<0.10.0)",
    "pyyaml (>=6.0.3,<7.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
